export const Position = {
    /**
     * Position of fragment within a compound word
     */
    ANY: "any",
    START: "start",
    END: "end",
    ALONE: "alone",
}


export const Type = {
    /**
     * Type of fragment; whether it can be used in forename, surname or either
     */
    ANY: "any",
    FORENAME: "forename",
    SURNAME: "surname",
}


export class Fragment {
    /**
     * Word fragment - the start or end of a forename and/or surname
     *
     * @param fragment Fragment of the word or the full word e.g. 'Octo' or 'Cheese'
     * @param position Position of the fragment within a compound word
     * @param type Type of fragment; whether it can be used in forename, surname or either
     * @param hyphenate Whether this fragment needs a hyphen before or after it
     * @param rude Whether this fragment is rude (sweary or lewd!!!)
     */

    constructor(
        fragment,
        {
            position = Position.ANY,
            type = Type.ANY,
            hyphenate = false,
            rude = false,
        },
    ) {
        this.fragment = fragment;
        this.position = position;
        this.type = type;
        this.hyphenate = hyphenate;
        this.rude = rude;
    }
}


export const fragments = [
    new Fragment(" 'core values' ", {}),
    new Fragment(" *skkrt* ", {}),
    new Fragment(" 4chan.pdf ", {}),
    new Fragment(" NaN ", {}),
    new Fragment(" Total War ", {}),
    new Fragment(" WHAT ", {}),
    new Fragment(" afraid of ", {}),
    new Fragment(" again!?", {position: Position.END, type: Type.SURNAME}),
    new Fragment(" against ", {}),
    new Fragment(" against the ", {position: Position.START, type: Type.SURNAME}),
    new Fragment(" al dente", {position: Position.END}),
    new Fragment(" all ", {}),
    new Fragment(" and ", {position: Position.START, type: Type.SURNAME}),
    new Fragment(" around the ", {}),
    new Fragment(" artful ", {}),
    new Fragment(" basically ", {}),
    new Fragment(" be ", {}),
    new Fragment(" behind ", {}),
    new Fragment(" circle back ", {}),
    new Fragment(" competitive ", {}),
    new Fragment(" concoction", {position: Position.END}),
    new Fragment(" cop ", {}),
    new Fragment(" courage ", {}),
    new Fragment(" cowardly ", {}),
    new Fragment(" cultured ", {}),
    new Fragment(" delayed due to ", {}),
    new Fragment(" dente", {position: Position.END}),
    new Fragment(" department of ", {}),
    new Fragment(" enchanted ", {}),
    new Fragment(" enjoyer ", {}),
    new Fragment(" ensconced ", {}),
    new Fragment(" extraordinaire ", {}),
    new Fragment(" feat. ", {}),
    new Fragment(" formerly known as ", {position: Position.START, type: Type.SURNAME}),
    new Fragment(" free range ", {}),
    new Fragment(" from Leeds", {position: Position.END, type: Type.SURNAME}),
    new Fragment(" ft. ", {}),
    new Fragment(" gates", {position: Position.END}),
    new Fragment(" go deeper ", {}),
    new Fragment(" good friend ", {}),
    new Fragment(" ho! ", {}),
    new Fragment(" huh? ", {}),
    new Fragment(" humanity", {position: Position.END}),
    new Fragment(" iii", {position: Position.END, type: Type.SURNAME}),
    new Fragment(" in ", {}),
    new Fragment(" in a trenchcoat", {position: Position.END, type: Type.SURNAME}),
    new Fragment(" in sales ", {}),
    new Fragment(" in session with Mark Riley", {position: Position.END}),
    new Fragment(" infeasible ", {}),
    new Fragment(" inquisition", {position: Position.END}),
    new Fragment(" inside ", {}),
    new Fragment(" iv", {position: Position.END, type: Type.SURNAME}),
    new Fragment(" long range", {position: Position.END}),
    new Fragment(" m8", {position: Position.END, type: Type.SURNAME}),
    new Fragment(" McGee", {position: Position.END}),
    new Fragment(" medium-rare ", {}),
    new Fragment(" merrily ", {}),
    new Fragment(" mom's spaghetti ", {}),
    new Fragment(" movement", {position: Position.END}),
    new Fragment(" noscope", {position: Position.END}),
    new Fragment(" null ", {}),
    new Fragment(" o' ", {}),
    new Fragment(" of holding", {position: Position.END, type: Type.SURNAME}),
    new Fragment(" oi! ", {}),
    new Fragment(" on BBC Radio 6music", {position: Position.END}),
    new Fragment(" one ", {}),
    new Fragment(" our kid ", {}),
    new Fragment(" our sponsor ", {}),
    new Fragment(" over ", {}),
    new Fragment(" ow! ", {}),
    new Fragment(" pal ", {}),
    new Fragment(" pursued by ", {}),
    new Fragment(" tea party", {position: Position.END}),
    new Fragment(" technically ", {}),
    new Fragment(" the wisp ", {}),
    new Fragment(" towers", {position: Position.END}),
    new Fragment(" umm ", {}),
    new Fragment(" undefined ", {}),
    new Fragment(" under ", {}),
    new Fragment(" upon ", {}),
    new Fragment(" well-done ", {}),
    new Fragment(" wireless ", {}),
    new Fragment(" without ", {position: Position.START, type: Type.SURNAME}),
    new Fragment(" x ", {}),
    new Fragment(" you! ", {}),
    new Fragment("! ", {position: Position.END}),
    new Fragment("!? ", {position: Position.END}),
    new Fragment("", {}),
    new Fragment("&block;&block;&block;&block;", {}),
    new Fragment("&trade;", {position: Position.END, type: Type.SURNAME}),
    new Fragment(", ", {position: Position.END}),
    new Fragment(", but I digress, ", {position: Position.END, type: Type.FORENAME}),
    new Fragment(", naturally", {position: Position.END, type: Type.SURNAME}),
    new Fragment("... ", {}),
    new Fragment(".exe", {position: Position.END, type: Type.SURNAME}),
    new Fragment("2", {}),
    new Fragment("2fast", {}),
    new Fragment("2furious", {}),
    new Fragment("360&deg; ", {position: Position.START}),
    new Fragment("3serious", {}),
    new Fragment("? ", {position: Position.END}),
    new Fragment("A.I. generated ", {position: Position.START}),
    new Fragment("O.G. ", {position: Position.START, type: Type.FORENAME}),
    new Fragment("able", {}),
    new Fragment("ache", {}),
    new Fragment("actually ", {position: Position.START, type: Type.FORENAME}),
    new Fragment("adblock", {position: Position.ALONE}),
    new Fragment("admiral ", {position: Position.START}),
    new Fragment("aeiou", {}),
    new Fragment("affair", {}),
    new Fragment("affairs", {}),
    new Fragment("aft", {}),
    new Fragment("afternoon", {}),
    new Fragment("aggression", {}),
    new Fragment("al ", {position: Position.START}),
    new Fragment("alabama", {}),
    new Fragment("alabaster", {}),
    new Fragment("alarm", {}),
    new Fragment("alarmed", {}),
    new Fragment("alarmist", {}),
    new Fragment("algae", {}),
    new Fragment("algal", {position: Position.START}),
    new Fragment("algorithm", {}),
    new Fragment("algorithmic", {}),
    new Fragment("alien", {}),
    new Fragment("all ", {position: Position.START}),
    new Fragment("allergic", {}),
    new Fragment("allergy", {}),
    new Fragment("alpaca", {}),
    new Fragment("alpha ", {position: Position.START}),
    new Fragment("always", {}),
    new Fragment("ambiance", {}),
    new Fragment("ambient", {}),
    new Fragment("ancient", {}),
    new Fragment("angel", {}),
    new Fragment("anger", {}),
    new Fragment("angle", {}),
    new Fragment("anti", {position: Position.START, hyphenate: true}),
    new Fragment("antidisestablishmentarianist", {position: Position.ALONE}),
    new Fragment("anus", {}),
    new Fragment("anxiety", {}),
    new Fragment("anxious", {}),
    new Fragment("aphex ", {position: Position.START, type: Type.FORENAME}),
    new Fragment("applicable", {position: Position.ALONE}),
    new Fragment("aqua", {position: Position.START}),
    new Fragment("arcade", {}),
    new Fragment("argh", {}),
    new Fragment("argue", {}),
    new Fragment("arguer", {}),
    new Fragment("aristo", {position: Position.START}),
    new Fragment("armchair", {}),
    new Fragment("armour", {}),
    new Fragment("arse", {}),
    new Fragment("art", {}),
    new Fragment("artist", {}),
    new Fragment("asbestos", {}),
    new Fragment("ashen", {}),
    new Fragment("aspic", {position: Position.ALONE}),
    new Fragment("ass", {}),
    new Fragment("astute", {position: Position.ALONE}),
    new Fragment("audacious", {position: Position.ALONE}),
    new Fragment("audio", {position: Position.START}),
    new Fragment("authentically ", {position: Position.START}),
    new Fragment("auto", {position: Position.START}),
    new Fragment("auto", {position: Position.START}),
    new Fragment("autosub", {position: Position.ALONE, type: Type.FORENAME}),
    new Fragment("avenged", {position: Position.ALONE}),
    new Fragment("average", {}),
    new Fragment("axe", {}),
    new Fragment("b. ", {position: Position.START, type: Type.SURNAME}),
    new Fragment("baby ", {position: Position.START}),
    new Fragment("back", {}),
    new Fragment("bacon", {}),
    new Fragment("badger", {}),
    new Fragment("badgerer", {}),
    new Fragment("badonka", {position: Position.START}),
    new Fragment("bae", {}),
    new Fragment("bag", {position: Position.END}),
    new Fragment("baggage", {}),
    new Fragment("bagger", {position: Position.END}),
    new Fragment("baggins", {}),
    new Fragment("baglan", {}),
    new Fragment("bags", {}),
    new Fragment("baiter", {position: Position.END}),
    new Fragment("baker", {}),
    new Fragment("ball", {}),
    new Fragment("baller", {}),
    new Fragment("ballin", {position: Position.ALONE}),
    new Fragment("balls", {position: Position.END}),
    new Fragment("bambi", {}),
    new Fragment("bambi", {}),
    new Fragment("bames", {position: Position.ALONE, type: Type.FORENAME}),
    new Fragment("ban", {}),
    new Fragment("banana", {}),
    new Fragment("bandit", {}),
    new Fragment("bane", {}),
    new Fragment("bang", {}),
    new Fragment("banged", {}),
    new Fragment("banger", {}),
    new Fragment("bangin", {}),
    new Fragment("banging", {}),
    new Fragment("banned", {}),
    new Fragment("bar", {}),
    new Fragment("barbed", {}),
    new Fragment("barber", {}),
    new Fragment("bare", {}),
    new Fragment("barely", {}),
    new Fragment("barf", {}),
    new Fragment("barge", {}),
    new Fragment("bargler", {}),
    new Fragment("bargy", {}),
    new Fragment("barrow", {}),
    new Fragment("based", {}),
    new Fragment("basement", {}),
    new Fragment("baster", {}),
    new Fragment("bat", {}),
    new Fragment("batch", {position: Position.END}),
    new Fragment("batman", {position: Position.ALONE}),
    new Fragment("battery", {}),
    new Fragment("battle", {}),
    new Fragment("batty", {}),
    new Fragment("bean", {}),
    new Fragment("beans", {position: Position.END}),
    new Fragment("bear", {}),
    new Fragment("beard", {}),
    new Fragment("beardy", {position: Position.START}),
    new Fragment("beast", {}),
    new Fragment("beastly", {}),
    new Fragment("beasty", {}),
    new Fragment("beaver", {}),
    new Fragment("bee", {}),
    new Fragment("bees", {}),
    new Fragment("beef", {}),
    new Fragment("beef", {}),
    new Fragment("beefy", {}),
    new Fragment("behind a VPN", {position: Position.ALONE, type: Type.SURNAME}),
    new Fragment("behind seven proxies", {position: Position.ALONE, type: Type.SURNAME}),
    new Fragment("behind the bike-sheds", {position: Position.ALONE, type: Type.SURNAME}),
    new Fragment("behind", {}),
    new Fragment("beige", {position: Position.START}),
    new Fragment("belay", {}),
    new Fragment("belayed", {}),
    new Fragment("belayer", {}),
    new Fragment("bell", {}),
    new Fragment("bellow", {}),
    new Fragment("bellows", {}),
    new Fragment("belly", {position: Position.END}),
    new Fragment("belter", {}),
    new Fragment("bench", {}),
    new Fragment("bendy", {}),
    new Fragment("benedict", {position: Position.ALONE, type: Type.FORENAME}),
    new Fragment("bepis", {}),
    new Fragment("berg", {position: Position.END}),
    new Fragment("berry", {}),
    new Fragment("bespectacled", {position: Position.ALONE}),
    new Fragment("bespoke", {}),
    new Fragment("bewitched", {}),
    new Fragment("bezos", {}),
    new Fragment("bichael", {}),
    new Fragment("bicycle", {}),
    new Fragment("big ", {position: Position.START}),
    new Fragment("biggins", {}),
    new Fragment("biggus", {position: Position.ALONE, type: Type.FORENAME}),
    new Fragment("bike", {}),
    new Fragment("bilbo", {}),
    new Fragment("binary", {}),
    new Fragment("bingo", {}),
    new Fragment("bingus", {}),
    new Fragment("bint", {}),
    new Fragment("bipass", {}),
    new Fragment("birb", {}),
    new Fragment("bird", {}),
    new Fragment("biscuit", {}),
    new Fragment("bismuth", {}),
    new Fragment("bite", {}),
    new Fragment("biter", {}),
    new Fragment("bitter", {}),
    new Fragment("bitters", {}),
    new Fragment("blag", {}),
    new Fragment("blagger", {}),
    new Fragment("blam", {}),
    new Fragment("blame", {}),
    new Fragment("blancmange", {position: Position.ALONE}),
    new Fragment("bland", {}),
    new Fragment("blart", {}),
    new Fragment("blast", {}),
    new Fragment("blasted", {}),
    new Fragment("blaster", {}),
    new Fragment("blasting", {}),
    new Fragment("blaze", {}),
    new Fragment("blazed", {}),
    new Fragment("blazer", {}),
    new Fragment("bleak", {}),
    new Fragment("bleary", {}),
    new Fragment("bleating", {}),
    new Fragment("bleddy", {}),
    new Fragment("bleedin", {}),
    new Fragment("bleeding", {}),
    new Fragment("bleep", {}),
    new Fragment("bleeping", {}),
    new Fragment("blend", {}),
    new Fragment("blender", {}),
    new Fragment("blessed", {}),
    new Fragment("blob", {}),
    new Fragment("blobber", {}),
    new Fragment("blobby", {}),
    new Fragment("blobs", {}),
    new Fragment("block", {}),
    new Fragment("blog", {}),
    new Fragment("blogger", {}),
    new Fragment("blogs", {}),
    new Fragment("blood", {}),
    new Fragment("bloody", {}),
    new Fragment("bloom", {}),
    new Fragment("bloomer", {}),
    new Fragment("blooms", {}),
    new Fragment("bloop", {}),
    new Fragment("blorp", {}),
    new Fragment("blower", {}),
    new Fragment("blubber", {}),
    new Fragment("blue", {}),
    new Fragment("blunder", {}),
    new Fragment("blunt", {}),
    new Fragment("blur", {}),
    new Fragment("blurb", {}),
    new Fragment("blurb", {}),
    new Fragment("blurst", {}),
    new Fragment("boaty", {position: Position.ALONE, type: Type.FORENAME}),
    new Fragment("body", {}),
    new Fragment("boeuf", {}),
    new Fragment("bog", {}),
    new Fragment("bogan", {}),
    new Fragment("boggle", {}),
    new Fragment("bogus", {position: Position.ALONE, type: Type.FORENAME}),
    new Fragment("boi", {position: Position.ALONE}),
    new Fragment("boi", {position: Position.END}),
    new Fragment("bolt", {}),
    new Fragment("bolus", {}),
    new Fragment("bomb", {}),
    new Fragment("bombs", {}),
    new Fragment("bonafide ", {position: Position.START}),
    new Fragment("bonce", {}),
    new Fragment("bone", {}),
    new Fragment("boner", {}),
    new Fragment("bones", {position: Position.END}),
    new Fragment("bongo", {}),
    new Fragment("bonk", {}),
    new Fragment("bonus", {}),
    new Fragment("boo", {}),
    new Fragment("boob", {}),
    new Fragment("boots", {}),
    new Fragment("booty", {}),
    new Fragment("booze", {}),
    new Fragment("boozy", {}),
    new Fragment("bore", {}),
    new Fragment("bored", {}),
    new Fragment("borg", {}),
    new Fragment("borger", {}),
    new Fragment("bork", {}),
    new Fragment("borks", {}),
    new Fragment("born", {}),
    new Fragment("born", {}),
    new Fragment("borne", {}),
    new Fragment("bort", {}),
    new Fragment("bother", {position: Position.START}),
    new Fragment("botherer", {position: Position.END}),
    new Fragment("bow", {}),
    new Fragment("bowel", {}),
    new Fragment("bowels", {}),
    new Fragment("bowl", {}),
    new Fragment("bowlen", {}),
    new Fragment("bowler", {}),
    new Fragment("bowler", {}),
    new Fragment("bowtie", {}),
    new Fragment("box", {}),
    new Fragment("brain", {}),
    new Fragment("brass", {}),
    new Fragment("brat", {}),
    new Fragment("bread", {}),
    new Fragment("breakfast", {}),
    new Fragment("breather", {}),
    new Fragment("breather", {}),
    new Fragment("breb", {}),
    new Fragment("brewer", {position: Position.END}),
    new Fragment("brie", {}),
    new Fragment("brigadier ", {position: Position.START}),
    new Fragment("brine", {}),
    new Fragment("briny", {}),
    new Fragment("bro", {}),
    new Fragment("brogue", {}),
    new Fragment("brogues", {}),
    new Fragment("brow", {}),
    new Fragment("brows", {}),
    new Fragment("brrrrrr", {}),
    new Fragment("brunch", {}),
    new Fragment("bubble", {}),
    new Fragment("bucket", {}),
    new Fragment("buckler", {}),
    new Fragment("buff", {}),
    new Fragment("buffer", {}),
    new Fragment("bug", {}),
    new Fragment("bugger", {position: Position.END}),
    new Fragment("buggy", {}),
    new Fragment("bugs", {}),
    new Fragment("bulba", {}),
    new Fragment("bull", {}),
    new Fragment("bully", {}),
    new Fragment("bum", {}),
    new Fragment("bumble", {}),
    new Fragment("bun", {}),
    new Fragment("bung", {position: Position.START}),
    new Fragment("bunny", {}),
    new Fragment("bunt", {}),
    new Fragment("burger", {}),
    new Fragment("burgler", {}),
    new Fragment("burns", {}),
    new Fragment("bus", {position: Position.END}),
    new Fragment("bush", {}),
    new Fragment("bussin", {}),
    new Fragment("busta", {}),
    new Fragment("bustard", {}),
    new Fragment("buster", {}),
    new Fragment("busty", {}),
    new Fragment("butt", {}),
    new Fragment("butter", {position: Position.START}),
    new Fragment("butterfly", {}),
    new Fragment("buzzard", {}),
    new Fragment("bypass", {}),
    new Fragment("c. ", {position: Position.START, type: Type.SURNAME}),
    new Fragment("cabbage", {position: Position.START}),
    new Fragment("caboose", {}),
    new Fragment("cake", {}),
    new Fragment("cakes", {}),
    new Fragment("calcium", {}),
    new Fragment("calm", {}),
    new Fragment("camper", {}),
    new Fragment("camper", {}),
    new Fragment("can", {}),
    new Fragment("canoe", {}),
    new Fragment("cans", {}),
    new Fragment("canyon", {}),
    new Fragment("canyoner", {}),
    new Fragment("cap", {}),
    new Fragment("capped", {}),
    new Fragment("caramel", {}),
    new Fragment("carp", {}),
    new Fragment("carpet", {}),
    new Fragment("casino", {}),
    new Fragment("castle", {}),
    new Fragment("casual ", {position: Position.START}),
    new Fragment("cat", {}),
    new Fragment("catcher", {}),
    new Fragment("cave", {}),
    new Fragment("caves", {}),
    new Fragment("cel", {position: Position.END}),
    new Fragment("cellar", {}),
    new Fragment("center", {}),
    new Fragment("centre", {}),
    new Fragment("cester", {}),
    new Fragment("cestershire", {position: Position.END}),
    new Fragment("chain", {}),
    new Fragment("chained", {}),
    new Fragment("chair", {}),
    new Fragment("chasm", {position: Position.END}),
    new Fragment("chauncy", {}),
    new Fragment("chav", {}),
    new Fragment("cheddar", {}),
    new Fragment("cheeks", {position: Position.END}),
    new Fragment("cheery", {position: Position.START}),
    new Fragment("cheese",  {}),
    new Fragment("cheese", {position: Position.END}),
    new Fragment("cheesy", {position: Position.START}),
    new Fragment("cheetoh", {}),
    new Fragment("chef", {}),
    new Fragment("cherry", {}),
    new Fragment("chesty", {position: Position.START}),
    new Fragment("chick", {}),
    new Fragment("chicken", {}),
    new Fragment("chief", {}),
    new Fragment("chimney", {}),
    new Fragment("chippy", {}),
    new Fragment("chips", {}),
    new Fragment("chirp", {}),
    new Fragment("chonk", {position: Position.END}),
    new Fragment("chonken", {}),
    new Fragment("chonker", {}),
    new Fragment("chonks", {position: Position.END}),
    new Fragment("chortle", {position: Position.START}),
    new Fragment("chortler", {position: Position.END}),
    new Fragment("chowder", {}),
    new Fragment("chowder", {}),
    new Fragment("chrome", {}),
    new Fragment("chu", {position: Position.END}),
    new Fragment("chub", {}),
    new Fragment("chubber", {}),
    new Fragment("chuckle", {}),
    new Fragment("chuckler", {}),
    new Fragment("chuckles", {}),
    new Fragment("chunder", {position: Position.START}),
    new Fragment("chungus", {}),
    new Fragment("chunk", {position: Position.END}),
    new Fragment("chunker", {}),
    new Fragment("chunks",  {position: Position.END}),
    new Fragment("chunky", {}),
    new Fragment("chunt", {}),
    new Fragment("chute", {}),
    new Fragment("chutney", {}),
    new Fragment("cider", {}),
    new Fragment("cistern", {}),
    new Fragment("claimant", {}),
    new Fragment("clam", {}),
    new Fragment("clam", {}),
    new Fragment("clapper", {}),
    new Fragment("clarence", {}),
    new Fragment("clean", {}),
    new Fragment("cleaner", {}),
    new Fragment("climber", {}),
    new Fragment("cloaca", {}),
    new Fragment("clock", {}),
    new Fragment("clot", {}),
    new Fragment("cloud", {}),
    new Fragment("cloudy", {}),
    new Fragment("club", {}),
    new Fragment("coach", {}),
    new Fragment("cock", {}),
    new Fragment("cockney", {}),
    new Fragment("code", {}),
    new Fragment("code", {}),
    new Fragment("coded", {}),
    new Fragment("cold", {}),
    new Fragment("colon", {}),
    new Fragment("commode", {}),
    new Fragment("compost", {}),
    new Fragment("composter", {}),
    new Fragment("computer", {}),
    new Fragment("comrade ", {position: Position.START}),
    new Fragment("conspiracy", {}),
    new Fragment("conspire", {}),
    new Fragment("constable", {position: Position.ALONE, type: Type.FORENAME}),
    new Fragment("constance ", {position: Position.START}),
    new Fragment("coo", {}),
    new Fragment("cookie", {}),
    new Fragment("copper", {}),
    new Fragment("copy of ", {position: Position.START, type: Type.FORENAME}),
    new Fragment("core", {}),
    new Fragment("cork", {}),
    new Fragment("corn", {}),
    new Fragment("corner", {}),
    new Fragment("corpse", {}),
    new Fragment("courier", {}),
    new Fragment("cowboy", {}),
    new Fragment("crab", {}),
    new Fragment("crack", {}),
    new Fragment("cracks", {}),
    new Fragment("craft", {}),
    new Fragment("crafter", {}),
    new Fragment("crafty", {}),
    new Fragment("crag", {}),
    new Fragment("craggy", {}),
    new Fragment("crammer", {}),
    new Fragment("crank", {}),
    new Fragment("crap", {}),
    new Fragment("crapper", {}),
    new Fragment("crapping", {}),
    new Fragment("craps", {}),
    new Fragment("crapulent", {position: Position.ALONE}),
    new Fragment("crass", {}),
    new Fragment("crat", {position: Position.END}),
    new Fragment("crazy", {}),
    new Fragment("cream", {}),
    new Fragment("creamy", {}),
    new Fragment("creep", {}),
    new Fragment("creeper", {}),
    new Fragment("creepy", {}),
    new Fragment("creme", {}),
    new Fragment("crentist", {position: Position.ALONE, type: Type.FORENAME}),
    new Fragment("cress", {}),
    new Fragment("cricket", {}),
    new Fragment("crime", {}),
    new Fragment("crimes", {}),
    new Fragment("crispy", {}),
    new Fragment("critical", {}),
    new Fragment("croak", {}),
    new Fragment("crocs", {}),
    new Fragment("cromulent", {position: Position.ALONE}),
    new Fragment("crone", {}),
    new Fragment("croney", {}),
    new Fragment("cronk", {}),
    new Fragment("crook", {}),
    new Fragment("crotch", {}),
    new Fragment("crow", {}),
    new Fragment("crumpet", {}),
    new Fragment("crunchy", {}),
    new Fragment("crunder", {position: Position.START}),
    new Fragment("crust", {}),
    new Fragment("crusty", {position: Position.START}),
    new Fragment("cry", {}),
    new Fragment("crypto", {}),
    new Fragment("cube", {}),
    new Fragment("cucumber", {position: Position.ALONE, type: Type.FORENAME}),
    new Fragment("cuddle", {}),
    new Fragment("cuddler", {}),
    new Fragment("cul-de-sac", {position: Position.ALONE, type: Type.SURNAME}),
    new Fragment("cumber", {position: Position.START}),
    new Fragment("cunning", {position: Position.START}),
    new Fragment("curd", {}),
    new Fragment("curried", {}),
    new Fragment("custard", {}),
    new Fragment("cwtch", {}),
    new Fragment("cyber", {position: Position.START}),
    new Fragment("d.j. ", {position: Position.START, type: Type.FORENAME}),
    new Fragment("daft", {position: Position.ALONE, type: Type.FORENAME}),
    new Fragment("daisy", {}),
    new Fragment("dam", {}),
    new Fragment("damage", {position: Position.ALONE, type: Type.SURNAME}),
    new Fragment("damn", {}),
    new Fragment("damned", {}),
    new Fragment("danger", {}),
    new Fragment("dapper", {}),
    new Fragment("dark", {position: Position.START}),
    new Fragment("dawg", {}),
    new Fragment("day", {}),
    new Fragment("de ", {position: Position.START, type: Type.SURNAME}),
    new Fragment("de-gloved", {}),
    new Fragment("de-glover", {}),
    new Fragment("deboned", {}),
    new Fragment("debug", {}),
    new Fragment("deciduous", {position: Position.ALONE}),
    new Fragment("deep", {}),
    new Fragment("deeper", {}),
    new Fragment("deer", {}),
    new Fragment("deez ", {position: Position.START, type: Type.SURNAME}),
    new Fragment("degenerate", {}),
    new Fragment("delay", {}),
    new Fragment("delayed", {}),
    new Fragment("delayer", {}),
    new Fragment("deliverance ", {position: Position.START, type: Type.FORENAME}),
    new Fragment("delivery", {}),
    new Fragment("demon", {}),
    new Fragment("dense", {}),
    new Fragment("dent", {}),
    new Fragment("dentist", {}),
    new Fragment("denty", {}),
    new Fragment("deputy ", {position: Position.START}),
    new Fragment("derp", {}),
    new Fragment("desert", {}),
    new Fragment("desire", {}),
    new Fragment("desireable", {}),
    new Fragment("dessert", {}),
    new Fragment("devil", {}),
    new Fragment("dick", {position: Position.ALONE, type: Type.FORENAME}),
    new Fragment("dicker", {}),
    new Fragment("digital", {}),
    new Fragment("dingus", {}),
    new Fragment("dink", {}),
    new Fragment("dinner", {}),
    new Fragment("dip", {}),
    new Fragment("dirt", {}),
    new Fragment("disco", {}),
    new Fragment("disenchanted", {}),
    new Fragment("ditch", {}),
    new Fragment("dizzy", {}),
    new Fragment("dobber", {}),
    new Fragment("dobby", {}),
    new Fragment("docile", {}),
    new Fragment("docker", {}),
    new Fragment("doctor", {}),
    new Fragment("dodger", {}),
    new Fragment("doer", {}),
    new Fragment("dog", {}),
    new Fragment("dogger", {}),
    new Fragment("dogging", {}),
    new Fragment("doink", {}),
    new Fragment("dolla", {}),
    new Fragment("dollar", {}),
    new Fragment("dolt", {}),
    new Fragment("dolt", {}),
    new Fragment("dome", {}),
    new Fragment("don ", {position: Position.START}),
    new Fragment("dong", {}),
    new Fragment("dongle", {}),
    new Fragment("dongus", {}),
    new Fragment("donk", {}),
    new Fragment("donut", {}),
    new Fragment("doom", {}),
    new Fragment("doon", {}),
    new Fragment("doot", {}),
    new Fragment("dork", {}),
    new Fragment("dottir", {position: Position.END}),
    new Fragment("dottir-dottir", {position: Position.END}),
    new Fragment("douche", {}),
    new Fragment("dough", {}),
    new Fragment("dowdy", {}),
    new Fragment("dragon", {}),
    new Fragment("drier", {}),
    new Fragment("drinker", {}),
    new Fragment("drippin", {}),
    new Fragment("driver", {position: Position.END}),
    new Fragment("droop", {}),
    new Fragment("drooping", {}),
    new Fragment("droopy", {}),
    new Fragment("drop", {position: Position.ALONE, type: Type.FORENAME}),
    new Fragment("drop", {position: Position.END}),
    new Fragment("dropping", {}),
    new Fragment("droppings", {}),
    new Fragment("drops", {}),
    new Fragment("drug", {}),
    new Fragment("drugs", {}),
    new Fragment("drum", {}),
    new Fragment("drummer", {}),
    new Fragment("dry", {}),
    new Fragment("dryer", {}),
    new Fragment("du ", {position: Position.START, type: Type.SURNAME}),
    new Fragment("dub", {position: Position.START}),
    new Fragment("duck", {}),
    new Fragment("dumb", {}),
    new Fragment("dummy", {}),
    new Fragment("dun", {}),
    new Fragment("dunder", {position: Position.START}),
    new Fragment("dungeon", {position: Position.START}),
    new Fragment("dunlop", {}),
    new Fragment("duo", {}),
    new Fragment("dusty", {}),
    new Fragment("dwarf", {}),
    new Fragment("dwarven", {}),
    new Fragment("dweller", {}),
    new Fragment("dyson", {}),
    new Fragment("ear", {}),
    new Fragment("early", {}),
    new Fragment("earth", {}),
    new Fragment("earthy", {}),
    new Fragment("east", {}),
    new Fragment("eater", {}),
    new Fragment("edge", {position: Position.START}),
    new Fragment("eel", {}),
    new Fragment("egg", {}),
    new Fragment("eggs", {position: Position.ALONE, type: Type.FORENAME}),
    new Fragment("elf", {}),
    new Fragment("elven", {}),
    new Fragment("email", {}),
    new Fragment("emanating ", {position: Position.START}),
    new Fragment("eminent ", {position: Position.START}),
    new Fragment("end", {position: Position.END}),
    new Fragment("energy", {}),
    new Fragment("enormous", {}),
    new Fragment("enraged ", {position: Position.START}),
    new Fragment("entrenched", {position: Position.ALONE}),
    new Fragment("error", {}),
    new Fragment("ether", {}),
    new Fragment("evening", {}),
    new Fragment("every", {}),
    new Fragment("exception", {}),
    new Fragment("exit", {}),
    new Fragment("extra", {position: Position.START}),
    new Fragment("extreme", {}),
    new Fragment("eyes", {}),
    new Fragment("f. ", {position: Position.START, type: Type.FORENAME}),
    new Fragment("face", {position: Position.END, type: Type.SURNAME}),
    new Fragment("faced", {}),
    new Fragment("factory", {}),
    new Fragment("faff", {}),
    new Fragment("fail", {}),
    new Fragment("failure", {}),
    new Fragment("falcon", {}),
    new Fragment("fam", {}),
    new Fragment("family", {}),
    new Fragment("fan", {}),
    new Fragment("fancier", {position: Position.END}),
    new Fragment("fancy", {}),
    new Fragment("fargler", {}),
    new Fragment("farmer ", {position: Position.START}),
    new Fragment("farmer", {position: Position.END}),
    new Fragment("fart", {}),
    new Fragment("farter", {position: Position.ALONE}),
    new Fragment("fast", {}),
    new Fragment("fatal", {}),
    new Fragment("fatboy", {position: Position.START}),
    new Fragment("feckless", {}),
    new Fragment("fecund", {position: Position.START}),
    new Fragment("feeler", {}),
    new Fragment("feet", {}),
    new Fragment("felcher", {}),
    new Fragment("feral", {position: Position.START}),
    new Fragment("ferry", {}),
    new Fragment("fiddle", {}),
    new Fragment("fiddler", {}),
    new Fragment("fight", {}),
    new Fragment("fine", {}),
    new Fragment("fire", {}),
    new Fragment("fired", {}),
    new Fragment("first", {}),
    new Fragment("fishy", {}),
    new Fragment("fist", {}),
    new Fragment("fit", {}),
    new Fragment("fitness", {}),
    new Fragment("flame", {}),
    new Fragment("flames", {}),
    new Fragment("flaming", {}),
    new Fragment("flamingo", {}),
    new Fragment("flapper", {}),
    new Fragment("flappin", {}),
    new Fragment("flaps", {position: Position.END}),
    new Fragment("fleisch", {}),
    new Fragment("flesh", {}),
    new Fragment("fleshy", {}),
    new Fragment("flobber", {}),
    new Fragment("flock", {}),
    new Fragment("flop", {}),
    new Fragment("flopper", {}),
    new Fragment("floppy", {}),
    new Fragment("flower", {}),
    new Fragment("fluffer", {}),
    new Fragment("flump", {}),
    new Fragment("flumper", {}),
    new Fragment("flush", {}),
    new Fragment("flushed", {}),
    new Fragment("flusher", {}),
    new Fragment("fog", {}),
    new Fragment("fogger", {}),
    new Fragment("foggy", {}),
    new Fragment("fondle", {}),
    new Fragment("fondler", {}),
    new Fragment("fone", {}),
    new Fragment("foo", {}),
    new Fragment("foof", {}),
    new Fragment("foot", {}),
    new Fragment("ford", {position: Position.ALONE}),
    new Fragment("fore", {}),
    new Fragment("fortune", {}),
    new Fragment("fowl", {}),
    new Fragment("fox", {}),
    new Fragment("frag", {}),
    new Fragment("fragment", {}),
    new Fragment("fragments", {}),
    new Fragment("frat", {}),
    new Fragment("frazzle", {}),
    new Fragment("frazzled", {}),
    new Fragment("frazzler", {}),
    new Fragment("free", {}),
    new Fragment("frodo", {}),
    new Fragment("frog", {}),
    new Fragment("frogger", {}),
    new Fragment("froggy", {}),
    new Fragment("fromage", {}),
    new Fragment("fruit", {}),
    new Fragment("fudge", {}),
    new Fragment("fun", {}),
    new Fragment("funk", {}),
    new Fragment("funky", {}),
    new Fragment("funny", {}),
    new Fragment("fur", {}),
    new Fragment("furry", {}),
    new Fragment("gag", {position: Position.END}),
    new Fragment("gamer", {}),
    new Fragment("gammon", {}),
    new Fragment("gangnam", {}),
    new Fragment("gangster", {position: Position.ALONE}),
    new Fragment("garage", {}),
    new Fragment("garden", {}),
    new Fragment("gargler", {}),
    new Fragment("garlic", {}),
    new Fragment("garms", {}),
    new Fragment("gas", {}),
    new Fragment("gash", {}),
    new Fragment("gasm", {position: Position.END}),
    new Fragment("gee", {position: Position.END}),
    new Fragment("geese", {}),
    new Fragment("geezer", {}),
    new Fragment("geist", {position: Position.END}),
    new Fragment("gel", {}),
    new Fragment("gelatinous", {position: Position.ALONE}),
    new Fragment("gerbil", {}),
    new Fragment("geriatric", {position: Position.ALONE}),
    new Fragment("geyser", {}),
    new Fragment("ghast", {position: Position.END}),
    new Fragment("ghast", {}),
    new Fragment("ghastly", {}),
    new Fragment("gherkin", {}),
    new Fragment("giggle", {}),
    new Fragment("giggler", {}),
    new Fragment("giggles", {}),
    new Fragment("gin", {}),
    new Fragment("git", {}),
    new Fragment("glad", {}),
    new Fragment("glam", {}),
    new Fragment("gland", {}),
    new Fragment("glands", {}),
    new Fragment("glandular", {}),
    new Fragment("glans", {}),
    new Fragment("glasses", {}),
    new Fragment("glisten", {}),
    new Fragment("glistening", {}),
    new Fragment("glitzy", {}),
    new Fragment("glizzy", {}),
    new Fragment("globe", {}),
    new Fragment("glove", {}),
    new Fragment("gloved", {}),
    new Fragment("glover", {}),
    new Fragment("gloves", {}),
    new Fragment("glue", {}),
    new Fragment("gnome", {}),
    new Fragment("gobbler", {position: Position.END}),
    new Fragment("goblin", {position: Position.END}),
    new Fragment("godspeed ", {position: Position.START}),
    new Fragment("gold", {}),
    new Fragment("golden", {}),
    new Fragment("golfer", {}),
    new Fragment("goo", {}),
    new Fragment("goob", {}),
    new Fragment("goober", {}),
    new Fragment("gooch", {}),
    new Fragment("goon", {position: Position.END}),
    new Fragment("gooner", {position: Position.END}),
    new Fragment("goop", {}),
    new Fragment("goose", {position: Position.END}),
    new Fragment("goosey", {position: Position.START}),
    new Fragment("goosey", {}),
    new Fragment("gorge", {}),
    new Fragment("gorgeous", {}),
    new Fragment("gorger", {}),
    new Fragment("gorges", {}),
    new Fragment("gorilla", {}),
    new Fragment("gorm", {}),
    new Fragment("gormen", {}),
    new Fragment("gorming", {}),
    new Fragment("goth", {}),
    new Fragment("gourd", {}),
    new Fragment("grabber", {position: Position.END}),
    new Fragment("grand", {}),
    new Fragment("grape", {}),
    new Fragment("grass", {}),
    new Fragment("grease", {}),
    new Fragment("great", {position: Position.ALONE}),
    new Fragment("green", {}),
    new Fragment("greens", {}),
    new Fragment("gregg's ", {position: Position.START, type: Type.FORENAME}),
    new Fragment("greige", {}),
    new Fragment("gremlin", {}),
    new Fragment("grift", {}),
    new Fragment("grifter", {}),
    new Fragment("grim", {}),
    new Fragment("grime", {}),
    new Fragment("grimes", {}),
    new Fragment("grimmer", {}),
    new Fragment("grin", {}),
    new Fragment("grind", {}),
    new Fragment("grinder", {}),
    new Fragment("grinds", {}),
    new Fragment("grinner", {}),
    new Fragment("grins", {}),
    new Fragment("gristle", {}),
    new Fragment("groin", {}),
    new Fragment("gronk", {}),
    new Fragment("ground", {}),
    new Fragment("grouse", {}),
    new Fragment("grouse", {}),
    new Fragment("grout", {}),
    new Fragment("grower", {}),
    new Fragment("growler", {}),
    new Fragment("grunt", {}),
    new Fragment("guano", {}),
    new Fragment("guerilla", {}),
    new Fragment("guff", {position: Position.END}),
    new Fragment("guitar", {}),
    new Fragment("gull", {}),
    new Fragment("gum", {}),
    new Fragment("gum", {}),
    new Fragment("gummer", {}),
    new Fragment("gun", {}),
    new Fragment("guppy", {}),
    new Fragment("guru", {}),
    new Fragment("gusset", {position: Position.END}),
    new Fragment("gutter", {}),
    new Fragment("gutters", {}),
    new Fragment("guzzler", {position: Position.END}),
    new Fragment("hacker", {}),
    new Fragment("hag", {}),
    new Fragment("haggis", {}),
    new Fragment("haggler", {}),
    new Fragment("hags", {}),
    new Fragment("hair", {position: Position.END}),
    new Fragment("hairy", {position: Position.ALONE}),
    new Fragment("ham", {}),
    new Fragment("hammer", {}),
    new Fragment("hands", {}),
    new Fragment("hanger", {position: Position.END}),
    new Fragment("hard", {}),
    new Fragment("hargler", {}),
    new Fragment("hat", {}),
    new Fragment("hatcher", {}),
    new Fragment("hate", {}),
    new Fragment("hated", {}),
    new Fragment("hater", {}),
    new Fragment("hates", {}),
    new Fragment("hatpin", {}),
    new Fragment("hatred", {position: Position.END}),
    new Fragment("hawk", {}),
    new Fragment("head", {position: Position.END}),
    new Fragment("head", {}),
    new Fragment("heady", {}),
    new Fragment("heap", {}),
    new Fragment("heaped", {}),
    new Fragment("heaps", {}),
    new Fragment("heart", {}),
    new Fragment("hearts", {}),
    new Fragment("hearty", {}),
    new Fragment("heavy", {}),
    new Fragment("hedge", {}),
    new Fragment("hedged", {}),
    new Fragment("hedger", {}),
    new Fragment("hedging", {}),
    new Fragment("hedgy", {}),
    new Fragment("heely", {position: Position.START}),
    new Fragment("heimer", {}),
    new Fragment("hell", {}),
    new Fragment("hella", {}),
    new Fragment("helmet", {}),
    new Fragment("hen", {}),
    new Fragment("henge", {}),
    new Fragment("herder", {}),
    new Fragment("hermit", {}),
    new Fragment("heron", {}),
    new Fragment("herring", {}),
    new Fragment("hipster", {}),
    new Fragment("hire", {}),
    new Fragment("hired ", {position: Position.START}),
    new Fragment("hoard", {}),
    new Fragment("hoarde", {}),
    new Fragment("hoarder", {}),
    new Fragment("hob", {}),
    new Fragment("holding", {}),
    new Fragment("hole", {position: Position.END}),
    new Fragment("holer", {}),
    new Fragment("holes", {}),
    new Fragment("holing", {}),
    new Fragment("holler", {}),
    new Fragment("hollow", {}),
    new Fragment("holo", {position: Position.START}),
    new Fragment("holy", {}),
    new Fragment("honey", {}),
    new Fragment("honk", {position: Position.END}),
    new Fragment("honker", {}),
    new Fragment("honking", {}),
    new Fragment("honks", {}),
    new Fragment("hoo", {}),
    new Fragment("hoof", {}),
    new Fragment("hooner", {}),
    new Fragment("hoot", {}),
    new Fragment("hooter", {}),
    new Fragment("hooves", {}),
    new Fragment("hope", {}),
    new Fragment("hopper", {}),
    new Fragment("horn", {position: Position.END}),
    new Fragment("horny", {}),
    new Fragment("horse", {}),
    new Fragment("hot", {}),
    new Fragment("hound", {}),
    new Fragment("house", {}),
    new Fragment("howdy", {}),
    new Fragment("howler", {}),
    new Fragment("howling", {}),
    new Fragment("huff", {}),
    new Fragment("huffer", {}),
    new Fragment("huffs", {}),
    new Fragment("hug", {}),
    new Fragment("huge", {}),
    new Fragment("hugger", {}),
    new Fragment("human", {}),
    new Fragment("hump", {}),
    new Fragment("humper", {}),
    new Fragment("humps", {}),
    new Fragment("hurse", {}),
    new Fragment("hurt", {}),
    new Fragment("husky", {position: Position.ALONE, type: Type.FORENAME}),
    new Fragment("hussy", {}),
    new Fragment("hut", {}),
    new Fragment("hypothetically ", {position: Position.START}),
    new Fragment("i can't believe it's not ", {position: Position.START, type: Type.FORENAME}),
    new Fragment("iced", {position: Position.START}),
    new Fragment("icey", {position: Position.START}),
    new Fragment("icles", {position: Position.ENDS}),
    new Fragment("idea", {}),
    new Fragment("ideal", {}),
    new Fragment("ideals", {}),
    new Fragment("ideas", {}),
    new Fragment("idle", {}),
    new Fragment("idol", {}),
    new Fragment("illegal", {}),
    new Fragment("in chat", {position: Position.ALONE, type: Type.SURNAME}),
    new Fragment("in the ", {position: Position.START, type: Type.SURNAME}),
    new Fragment("incensed", {}),
    new Fragment("infected", {}),
    new Fragment("infectious", {}),
    new Fragment("ingus", {position: Position.END}),
    new Fragment("insider", {}),
    new Fragment("insta", {position: Position.START}),
    new Fragment("intel", {}),
    new Fragment("iron", {}),
    new Fragment("irregular", {}),
    new Fragment("it's always ", {position: Position.START, type: Type.FORENAME}),
    new Fragment("jabber", {}),
    new Fragment("jacker", {}),
    new Fragment("jam", {}),
    new Fragment("jeans", {}),
    new Fragment("jelly", {}),
    new Fragment("jet", {}),
    new Fragment("jets", {}),
    new Fragment("job", {}),
    new Fragment("jobber", {}),
    new Fragment("jobber", {}),
    new Fragment("jobby", {}),
    new Fragment("jockey", {position: Position.END}),
    new Fragment("jog", {}),
    new Fragment("jogger", {}),
    new Fragment("jond", {position: Position.ALONE, type: Type.SURNAME}),
    new Fragment("joppo", {}),
    new Fragment("jort", {}),
    new Fragment("jorter", {}),
    new Fragment("jorting", {}),
    new Fragment("jorts", {}),
    new Fragment("jorts", {}),
    new Fragment("joy", {}),
    new Fragment("judge", {}),
    new Fragment("juggler", {position: Position.END}),
    new Fragment("juice", {}),
    new Fragment("juicer", {}),
    new Fragment("juicy", {}),
    new Fragment("jumbo", {}),
    new Fragment("jumper", {}),
    new Fragment("jungle", {}),
    new Fragment("junk", {}),
    new Fragment("junker", {}),
    new Fragment("junky", {}),
    new Fragment("kebab", {}),
    new Fragment("keeper", {position: Position.END}),
    new Fragment("keg", {}),
    new Fragment("kernel", {}),
    new Fragment("kettle", {}),
    new Fragment("keyboard ", {}),
    new Fragment("keygen ", {}),
    new Fragment("kid", {}),
    new Fragment("kidney", {}),
    new Fragment("kin", {}),
    new Fragment("king", {}),
    new Fragment("kiwi", {}),
    new Fragment("klaxon", {}),
    new Fragment("klingon", {}),
    new Fragment("knitter", {}),
    new Fragment("knob", {}),
    new Fragment("knuckle", {}),
    new Fragment("korn", {}),
    new Fragment("krampus", {}),
    new Fragment("kun", {position: Position.END, hyphenate: true}),
    new Fragment("lacy", {}),
    new Fragment("lad", {}),
    new Fragment("lady", {}),
    new Fragment("land", {}),
    new Fragment("lard", {}),
    new Fragment("lardon", {}),
    new Fragment("laser", {}),
    new Fragment("lass", {}),
    new Fragment("last", {}),
    new Fragment("late", {}),
    new Fragment("latex", {}),
    new Fragment("launderer", {}),
    new Fragment("lavatory", {}),
    new Fragment("lavender", {}),
    new Fragment("law", {}),
    new Fragment("lawn", {}),
    new Fragment("lawyer", {}),
    new Fragment("lazy", {}),
    new Fragment("lead", {}),
    new Fragment("leaf", {}),
    new Fragment("leafy", {}),
    new Fragment("least", {}),
    new Fragment("leet", {}),
    new Fragment("legally ", {position: Position.START}),
    new Fragment("legs", {}),
    new Fragment("less", {}),
    new Fragment("lettuce", {}),
    new Fragment("lice", {}),
    new Fragment("licensed", {}),
    new Fragment("lichen", {}),
    new Fragment("licker", {position: Position.END}),
    new Fragment("life", {}),
    new Fragment("light", {}),
    new Fragment("lightning", {}),
    new Fragment("ligma ", {position: Position.START}),
    new Fragment("like", {}),
    new Fragment("liked", {}),
    new Fragment("liker", {position: Position.END}),
    new Fragment("likes", {}),
    new Fragment("lilac", {}),
    new Fragment("lilly", {}),
    new Fragment("lime", {}),
    new Fragment("limey", {}),
    new Fragment("lingus", {position: Position.END}),
    new Fragment("lips", {position: Position.END}),
    new Fragment("lipwig", {position: Position.ALONE, type: Type.SURNAME}),
    new Fragment("lit", {}),
    new Fragment("literally ", {position: Position.START}),
    new Fragment("little ", {position: Position.START}),
    new Fragment("liver", {}),
    new Fragment("llama", {}),
    new Fragment("load", {}),
    new Fragment("loadsa", {position: Position.START}),
    new Fragment("loaf", {}),
    new Fragment("lofty", {}),
    new Fragment("long range", {position: Position.ALONE, type: Type.SURNAME}),
    new Fragment("loosey", {position: Position.ALONE, type: Type.FORENAME}),
    new Fragment("lord", {}),
    new Fragment("lore", {}),
    new Fragment("lorge", {position: Position.ALONE, type: Type.FORENAME}),
    new Fragment("lorry", {}),
    new Fragment("loser", {}),
    new Fragment("lover", {}),
    new Fragment("lubber", {}),
    new Fragment("ludicrous", {position: Position.ALONE, type: Type.FORENAME}),
    new Fragment("lugger", {}),
    new Fragment("lump", {}),
    new Fragment("lumper", {}),
    new Fragment("lumps", {}),
    new Fragment("lunch", {}),
    new Fragment("lung", {}),
    new Fragment("lungs", {}),
    new Fragment("m.c. ", {position: Position.START, type: Type.FORENAME}),
    new Fragment("Mac", {position: Position.START, type: Type.SURNAME, hyphenate: true}),
    new Fragment("machine", {}),
    new Fragment("mad", {}),
    new Fragment("mage", {}),
    new Fragment("magic", {}),
    new Fragment("magnet", {}),
    new Fragment("magneto", {position: Position.START}),
    new Fragment("magpie", {}),
    new Fragment("major ", {position: Position.START, type: Type.FORENAME}),
    new Fragment("malfunction", {position: Position.ALONE, type: Type.SURNAME}),
    new Fragment("malice", {}),
    new Fragment("mancy", {}),
    new Fragment("mandem", {}),
    new Fragment("manganese", {position: Position.END}),
    new Fragment("mangy", {}),
    new Fragment("mare", {position: Position.END}),
    new Fragment("margarine", {position: Position.ALONE}),
    new Fragment("margarine", {position: Position.ALONE}),
    new Fragment("marigold", {}),
    new Fragment("market", {}),
    new Fragment("marrow", {}),
    new Fragment("mars", {}),
    new Fragment("mash", {}),
    new Fragment("masher", {}),
    new Fragment("massive", {}),
    new Fragment("master", {position: Position.START}),
    new Fragment("maths", {}),
    new Fragment("max", {position: Position.ALONE, type: Type.FORENAME}),
    new Fragment("maxxer", {position: Position.END}),
    new Fragment("Mc", {position: Position.START, type: Type.SURNAME, hyphenate: true}),
    new Fragment("meat", {}),
    new Fragment("mega", {position: Position.START}),
    new Fragment("mellow", {}),
    new Fragment("meme", {position: Position.START}),
    new Fragment("menace", {}),
    new Fragment("meow", {}),
    new Fragment("metal", {}),
    new Fragment("mew", {}),
    new Fragment("mice", {}),
    new Fragment("micro", {position: Position.START}),
    new Fragment("middle", {}),
    new Fragment("midship", {}),
    new Fragment("mifflin", {}),
    new Fragment("miles", {}),
    new Fragment("militant ", {position: Position.START}),
    new Fragment("milk", {}),
    new Fragment("milker", {}),
    new Fragment("milkshake", {position: Position.ALONE}),
    new Fragment("milque", {}),
    new Fragment("minger", {}),
    new Fragment("mini", {position: Position.START}),
    new Fragment("mint", {}),
    new Fragment("minute", {}),
    new Fragment("missing", {}),
    new Fragment("mite", {}),
    new Fragment("mites", {}),
    new Fragment("mix", {}),
    new Fragment("mixed", {}),
    new Fragment("mode", {}),
    new Fragment("moist", {position: Position.START}),
    new Fragment("money", {}),
    new Fragment("mongoose", {}),
    new Fragment("monk", {}),
    new Fragment("monkey", {}),
    new Fragment("monster", {}),
    new Fragment("moo", {}),
    new Fragment("mooing", {}),
    new Fragment("moon", {}),
    new Fragment("moose", {}),
    new Fragment("more", {}),
    new Fragment("morning", {}),
    new Fragment("most", {}),
    new Fragment("motor", {}),
    new Fragment("mournful", {}),
    new Fragment("mourning", {}),
    new Fragment("mouse", {}),
    new Fragment("mouth", {}),
    new Fragment("mow", {}),
    new Fragment("mower", {}),
    new Fragment("mucker", {}),
    new Fragment("mucky", {}),
    new Fragment("mud", {}),
    new Fragment("muff", {}),
    new Fragment("muffin", {}),
    new Fragment("muffle", {}),
    new Fragment("muffler", {}),
    new Fragment("mumble", {position: Position.START}),
    new Fragment("mumbler", {position: Position.END}),
    new Fragment("munch", {}),
    new Fragment("muncher", {}),
    new Fragment("munted", {}),
    new Fragment("murder", {}),
    new Fragment("muscle", {}),
    new Fragment("muscled", {}),
    new Fragment("mush", {}),
    new Fragment("musher", {}),
    new Fragment("musk", {}),
    new Fragment("musky", {}),
    new Fragment("mustard", {}),
    new Fragment("my ", {position: Position.START}),
    new Fragment("mystery", {}),
    new Fragment("nargler", {}),
    new Fragment("narrow", {}),
    new Fragment("neck", {}),
    new Fragment("nectar", {}),
    new Fragment("nectar", {}),
    new Fragment("nerd", {}),
    new Fragment("never", {}),
    new Fragment("nickel", {}),
    new Fragment("night", {}),
    new Fragment("no! ", {position: Position.START}),
    new Fragment("nob", {}),
    new Fragment("nobber", {}),
    new Fragment("nobody suspects ", {position: Position.START, type: Type.FORENAME}),
    new Fragment("nodule", {}),
    new Fragment("noddy", {}),
    new Fragment("noodle", {}),
    new Fragment("noodler", {}),
    new Fragment("noodles", {}),
    new Fragment("noodling", {}),
    new Fragment("noon", {}),
    new Fragment("nope", {}),
    new Fragment("normal", {}),
    new Fragment("normie", {}),
    new Fragment("north", {}),
    new Fragment("nose", {}),
    new Fragment("not", {position: Position.START}),
    new Fragment("note", {}),
    new Fragment("notorious", {position: Position.ALONE}),
    new Fragment("nouveau", {hyphenate: true}),
    new Fragment("nova", {}),
    new Fragment("novelty", {}),
    new Fragment("nuisance", {}),
    new Fragment("null", {}),
    new Fragment("nun", {}),
    new Fragment("nut", {}),
    new Fragment("nuts", {position: Position.END}),
    new Fragment("nutter", {}),
    new Fragment("nuzzler", {position: Position.END}),
    new Fragment("oats", {}),
    new Fragment("oblong", {}),
    new Fragment("obtuse", {position: Position.ALONE}),
    new Fragment("octo", {position: Position.START}),
    new Fragment("octopus", {position: Position.ALONE}),
    new Fragment("odorous", {position: Position.ALONE, type: Type.FORENAME}),
    new Fragment("odour", {}),
    new Fragment("of ", {position: Position.START, type: Type.SURNAME}),
    new Fragment("office", {}),
    new Fragment("officer", {}),
    new Fragment("ogre", {}),
    new Fragment("oh! ", {position: Position.START}),
    new Fragment("oid", {position: Position.END}),
    new Fragment("ointment", {}),
    new Fragment("old ", {position: Position.START, type: Type.FORENAME}),
    new Fragment("omelette", {}),
    new Fragment("ominous ", {position: Position.START}),
    new Fragment("on ice", {}),
    new Fragment("on the rocks", {}),
    new Fragment("on thin ice", {}),
    new Fragment("onion", {}),
    new Fragment("ook", {}),
    new Fragment("oops! ", {position: Position.START}),
    new Fragment("oops", {}),
    new Fragment("open", {position: Position.START}),
    new Fragment("oppa", {}),
    new Fragment("orangu", {position: Position.START}),
    new Fragment("orb", {}),
    new Fragment("oregano", {}),
    new Fragment("organ", {}),
    new Fragment("organic ", {position: Position.START}),
    new Fragment("organs", {}),
    new Fragment("orientated", {}),
    new Fragment("oriented", {}),
    new Fragment("original", {position: Position.ALONE}),
    new Fragment("ornate", {}),
    new Fragment("ornery", {}),
    new Fragment("otter", {}),
    new Fragment("owanes", {}),
    new Fragment("owl", {}),
    new Fragment("owlish", {}),
    new Fragment("owo", {}),
    new Fragment("packer", {}),
    new Fragment("packing", {}),
    new Fragment("paid", {}),
    new Fragment("pain", {}),
    new Fragment("painter", {}),
    new Fragment("pal", {}),
    new Fragment("pale", {}),
    new Fragment("panic", {}),
    new Fragment("panicked", {}),
    new Fragment("panicky", {}),
    new Fragment("pantry", {}),
    new Fragment("pants", {position: Position.END}),
    new Fragment("panty", {}),
    new Fragment("parma", {}),
    new Fragment("part", {}),
    new Fragment("parts", {}),
    new Fragment("party", {}),
    new Fragment("pasta", {}),
    new Fragment("pastel", {}),
    new Fragment("pasty", {}),
    new Fragment("patch", {position: Position.END}),
    new Fragment("pay", {}),
    new Fragment("payer", {}),
    new Fragment("pea", {}),
    new Fragment("peace", {}),
    new Fragment("peach", {}),
    new Fragment("peachy", {position: Position.START}),
    new Fragment("pear", {}),
    new Fragment("peeling", {}),
    new Fragment("peen", {}),
    new Fragment("peep", {}),
    new Fragment("peeper", {}),
    new Fragment("peepin", {}),
    new Fragment("peeping", {}),
    new Fragment("peg", {}),
    new Fragment("pellet", {}),
    new Fragment("pellets", {}),
    new Fragment("peng", {}),
    new Fragment("penguin", {}),
    new Fragment("pepper", {}),
    new Fragment("perfect", {}),
    new Fragment("person", {}),
    new Fragment("petal", {}),
    new Fragment("pharma", {}),
    new Fragment("pheasant", {}),
    new Fragment("phile", {position: Position.END}),
    new Fragment("phlegm", {}),
    new Fragment("phobe", {position: Position.END}),
    new Fragment("phone", {}),
    new Fragment("piano", {}),
    new Fragment("pickle", {}),
    new Fragment("pickled", {}),
    new Fragment("pickler", {}),
    new Fragment("pie", {}),
    new Fragment("piecemeal", {position: Position.ALONE}),
    new Fragment("pig", {position: Position.END}),
    new Fragment("pigeon", {}),
    new Fragment("pika", {}),
    new Fragment("pile", {}),
    new Fragment("piles", {}),
    new Fragment("pill", {}),
    new Fragment("pilled", {}),
    new Fragment("pilot", {}),
    new Fragment("pilsbury", {position: Position.START, type: Type.FORENAME}),
    new Fragment("pink", {}),
    new Fragment("pinky", {}),
    new Fragment("pipe", {}),
    new Fragment("pizza", {}),
    new Fragment("planet", {}),
    new Fragment("plant", {}),
    new Fragment("plasma", {}),
    new Fragment("pleasant", {}),
    new Fragment("pleasant", {}),
    new Fragment("pleasing", {}),
    new Fragment("pleasure", {}),
    new Fragment("plop", {}),
    new Fragment("plopper", {}),
    new Fragment("plops", {}),
    new Fragment("plover", {}),
    new Fragment("plow", {}),
    new Fragment("plower", {}),
    new Fragment("pluck", {}),
    new Fragment("plucker", {}),
    new Fragment("plum", {}),
    new Fragment("plump", {}),
    new Fragment("plunder", {}),
    new Fragment("plunger", {}),
    new Fragment("pluto", {}),
    new Fragment("pog", {}),
    new Fragment("pointed", {}),
    new Fragment("pointer", {}),
    new Fragment("poke", {}),
    new Fragment("poker", {}),
    new Fragment("pole", {}),
    new Fragment("police", {}),
    new Fragment("polytetrafluoroethylene", {position: Position.ALONE}),
    new Fragment("pond", {}),
    new Fragment("ponder", {}),
    new Fragment("pondering", {}),
    new Fragment("ponderous", {}),
    new Fragment("ponds", {}),
    new Fragment("pooh", {}),
    new Fragment("pool", {}),
    new Fragment("poor", {}),
    new Fragment("poppy", {}),
    new Fragment("pork", {}),
    new Fragment("porker", {position: Position.END}),
    new Fragment("porridge", {}),
    new Fragment("port", {}),
    new Fragment("porta", {position: Position.START}),
    new Fragment("portal", {}),
    new Fragment("post", {position: Position.START, hyphenate: true}),
    new Fragment("poster", {position: Position.END}),
    new Fragment("potate", {}),
    new Fragment("potato", {}),
    new Fragment("potch", {}),
    new Fragment("potent", {position: Position.ALONE}),
    new Fragment("pots", {}),
    new Fragment("potter", {}),
    new Fragment("potty", {}),
    new Fragment("pound", {}),
    new Fragment("power", {}),
    new Fragment("powers", {position: Position.END}),
    new Fragment("pratchett", {position: Position.ALONE, type: Type.SURNAME}),
    new Fragment("pratchett", {}),
    new Fragment("prattler", {}),
    new Fragment("precious", {}),
    new Fragment("prefect", {position: Position.ALONE}),
    new Fragment("presence", {}),
    new Fragment("pro", {position: Position.START, hyphenate: true}),
    new Fragment("process", {}),
    new Fragment("prop", {}),
    new Fragment("proprietary ", {position: Position.START}),
    new Fragment("prostrate", {}),
    new Fragment("protest", {}),
    new Fragment("proto", {position: Position.START}),
    new Fragment("proud", {}),
    new Fragment("pubis", {}),
    new Fragment("pudding", {position: Position.START}),
    new Fragment("puddle", {}),
    new Fragment("puff", {}),
    new Fragment("puffin", {}),
    new Fragment("pun", {}),
    new Fragment("pungent", {}),
    new Fragment("punk", {}),
    new Fragment("punny", {}),
    new Fragment("punt", {}),
    new Fragment("punter", {}),
    new Fragment("punting", {}),
    new Fragment("purple", {}),
    new Fragment("pus", {}),
    new Fragment("puss", {}),
    new Fragment("pustular", {}),
    new Fragment("pustule", {}),
    new Fragment("pustules", {}),
    new Fragment("queef", {}),
    new Fragment("queen", {}),
    new Fragment("questionable", {position: Position.ALONE, type: Type.FORENAME}),
    new Fragment("quiche", {}),
    new Fragment("quids", {}),
    new Fragment("racer", {}),
    new Fragment("rad", {}),
    new Fragment("radio", {}),
    new Fragment("rag", {}),
    new Fragment("rage", {}),
    new Fragment("rags", {}),
    new Fragment("rancid", {}),
    new Fragment("raptor", {}),
    new Fragment("rat", {}),
    new Fragment("rattler", {}),
    new Fragment("raver", {}),
    new Fragment("raw", {}),
    new Fragment("really ", {position: Position.START}),
    new Fragment("reboot", {}),
    new Fragment("reddit", {}),
    new Fragment("reeeeeee", {}),
    new Fragment("refactor", {}),
    new Fragment("regular", {}),
    new Fragment("rekt", {}),
    new Fragment("remus", {}),
    new Fragment("respect", {}),
    new Fragment("respects", {}),
    new Fragment("retch", {}),
    new Fragment("retching", {}),
    new Fragment("revenge", {}),
    new Fragment("ribbed", {}),
    new Fragment("rich", {}),
    new Fragment("rider", {}),
    new Fragment("rigid", {}),
    new Fragment("rincewind", {position: Position.ALONE, type: Type.FORENAME}),
    new Fragment("ring", {}),
    new Fragment("ringer", {}),
    new Fragment("roach", {}),
    new Fragment("roadman", {position: Position.ALONE, type: Type.FORENAME}),
    new Fragment("robust", {}),
    new Fragment("rocker", {}),
    new Fragment("rocket", {position: Position.END}),
    new Fragment("rocky", {}),
    new Fragment("rogue", {}),
    new Fragment("roguelike", {}),
    new Fragment("roid", {}),
    new Fragment("rollin", {}),
    new Fragment("rolling", {}),
    new Fragment("rollins", {}),
    new Fragment("romulus", {}),
    new Fragment("rope", {}),
    new Fragment("rough", {}),
    new Fragment("round", {}),
    new Fragment("rubber", {}),
    new Fragment("rug", {}),
    new Fragment("rug", {}),
    new Fragment("rum", {}),
    new Fragment("rumps", {}),
    new Fragment("rumpus", {}),
    new Fragment("sac", {}),
    new Fragment("sacks", {position: Position.END}),
    new Fragment("sad", {}),
    new Fragment("sag", {}),
    new Fragment("sage", {}),
    new Fragment("saggy", {}),
    new Fragment("saint", {}),
    new Fragment("salad", {}),
    new Fragment("salmon", {}),
    new Fragment("salsa", {}),
    new Fragment("salty", {}),
    new Fragment("sample", {}),
    new Fragment("sampler", {}),
    new Fragment("san", {position: Position.END, hyphenate: true}),
    new Fragment("sand", {}),
    new Fragment("sandwich", {}),
    new Fragment("sandwiched", {}),
    new Fragment("sandy", {}),
    new Fragment("sap", {}),
    new Fragment("satin", {}),
    new Fragment("sauce", {}),
    new Fragment("saucy", {}),
    new Fragment("saur", {position: Position.END}),
    new Fragment("saurus", {position: Position.END}),
    new Fragment("sausage", {}),
    new Fragment("sauvage", {}),
    new Fragment("savage", {}),
    new Fragment("saxo", {position: Position.START}),
    new Fragment("scare", {}),
    new Fragment("scat", {position: Position.START}),
    new Fragment("scenic", {}),
    new Fragment("scent", {}),
    new Fragment("scented", {}),
    new Fragment("schwoo", {}),
    new Fragment("scone", {}),
    new Fragment("scope", {}),
    new Fragment("scraps", {}),
    new Fragment("screw", {}),
    new Fragment("scroller", {}),
    new Fragment("scrump", {}),
    new Fragment("scrumper", {}),
    new Fragment("scrumpy", {}),
    new Fragment("scum", {}),
    new Fragment("scummer", {}),
    new Fragment("scummy", {}),
    new Fragment("sea", {}),
    new Fragment("seagull", {}),
    new Fragment("seal", {}),
    new Fragment("secret", {}),
    new Fragment("seed", {}),
    new Fragment("seedy", {}),
    new Fragment("seer", {}),
    new Fragment("segway", {}),
    new Fragment("semi", {position: Position.START, hyphenate: true}),
    new Fragment("sensual", {}),
    new Fragment("sentient ", {position: Position.ALONE}),
    new Fragment("serious", {}),
    new Fragment("services", {position: Position.END}),
    new Fragment("set", {}),
    new Fragment("sevenfold", {position: Position.ALONE}),
    new Fragment("shadow", {}),
    new Fragment("shady", {}),
    new Fragment("shaft", {}),
    new Fragment("shafts", {}),
    new Fragment("shaker", {position: Position.END}),
    new Fragment("shallow", {}),
    new Fragment("shanks", {}),
    new Fragment("shard", {}),
    new Fragment("shards", {}),
    new Fragment("sharp", {}),
    new Fragment("shart", {}),
    new Fragment("sharter", {}),
    new Fragment("sharting", {}),
    new Fragment("sheep", {}),
    new Fragment("sheisty", {}),
    new Fragment("shell", {}),
    new Fragment("shingled", {}),
    new Fragment("shiny", {}),
    new Fragment("ship", {}),
    new Fragment("shipper", {}),
    new Fragment("shirtless", {}),
    new Fragment("shoes", {}),
    new Fragment("shoot", {}),
    new Fragment("shoots", {}),
    new Fragment("short", {}),
    new Fragment("shorts", {}),
    new Fragment("shorts", {}),
    new Fragment("shout", {}),
    new Fragment("shouter", {}),
    new Fragment("shouty", {}),
    new Fragment("shower", {}),
    new Fragment("shrek", {}),
    new Fragment("shrew", {}),
    new Fragment("shrewd", {}),
    new Fragment("shrewd", {}),
    new Fragment("shriek", {}),
    new Fragment("shrieker", {}),
    new Fragment("shrieking", {}),
    new Fragment("shrink", {}),
    new Fragment("shrinked", {}),
    new Fragment("shrinker", {}),
    new Fragment("shunt", {}),
    new Fragment("shunt", {}),
    new Fragment("shunter", {}),
    new Fragment("shunter", {}),
    new Fragment("shuttle", {}),
    new Fragment("shuttle", {}),
    new Fragment("shy", {}),
    new Fragment("sick", {}),
    new Fragment("silica", {}),
    new Fragment("silicate", {}),
    new Fragment("silly", {position: Position.START}),
    new Fragment("silver", {}),
    new Fragment("silver", {}),
    new Fragment("sim", {}),
    new Fragment("sin", {}),
    new Fragment("sinewave", {position: Position.ALONE}),
    new Fragment("sinister ", {position: Position.START}),
    new Fragment("sinner", {}),
    new Fragment("sitter", {}),
    new Fragment("skin", {}),
    new Fragment("slack", {}),
    new Fragment("slap", {}),
    new Fragment("slapper", {position: Position.END}),
    new Fragment("slarty", {}),
    new Fragment("slat", {}),
    new Fragment("slaw", {}),
    new Fragment("sledge", {}),
    new Fragment("slice", {position: Position.END}),
    new Fragment("slice", {}),
    new Fragment("slim", {}),
    new Fragment("slime", {}),
    new Fragment("slimy", {}),
    new Fragment("slither", {}),
    new Fragment("slob", {}),
    new Fragment("slobber", {}),
    new Fragment("slog", {}),
    new Fragment("slogger", {}),
    new Fragment("slonk", {}),
    new Fragment("slop", {}),
    new Fragment("slope", {}),
    new Fragment("slosher", {}),
    new Fragment("slot", {}),
    new Fragment("slots", {}),
    new Fragment("slotted", {}),
    new Fragment("slow", {}),
    new Fragment("slug", {}),
    new Fragment("slugger", {}),
    new Fragment("sluggy", {}),
    new Fragment("slurp", {}),
    new Fragment("slurper", {position: Position.END}),
    new Fragment("slurry", {}),
    new Fragment("small", {position: Position.START}),
    new Fragment("smeagol", {}),
    new Fragment("smear", {}),
    new Fragment("smeary", {}),
    new Fragment("smearer", {}),
    new Fragment("smeg", {}),
    new Fragment("smegger", {}),
    new Fragment("smeggy", {}),
    new Fragment("smeller", {position: Position.END}),
    new Fragment("smench", {}),
    new Fragment("smile", {}),
    new Fragment("smint", {}),
    new Fragment("smints", {}),
    new Fragment("smithers", {}),
    new Fragment("smock", {}),
    new Fragment("smog", {}),
    new Fragment("smogger", {}),
    new Fragment("smoked", {}),
    new Fragment("smooth", {}),
    new Fragment("smort", {}),
    new Fragment("smug", {}),
    new Fragment("smuggler", {position: Position.END}),
    new Fragment("smush", {}),
    new Fragment("snack", {}),
    new Fragment("snail", {}),
    new Fragment("snail", {}),
    new Fragment("snake", {}),
    new Fragment("snap", {}),
    new Fragment("snapper", {}),
    new Fragment("snatch", {}),
    new Fragment("snatcher", {}),
    new Fragment("sneeze", {}),
    new Fragment("snek", {}),
    new Fragment("sniffer", {}),
    new Fragment("sniffle", {}),
    new Fragment("snitch", {}),
    new Fragment("snitcher", {}),
    new Fragment("snog", {}),
    new Fragment("snogger", {}),
    new Fragment("snooker", {}),
    new Fragment("snoot", {position: Position.END}),
    new Fragment("snooty", {position: Position.START}),
    new Fragment("snorkler", {position: Position.END}),
    new Fragment("snorkler", {}),
    new Fragment("snorter", {position: Position.END}),
    new Fragment("snot", {}),
    new Fragment("snuff", {position: Position.END}),
    new Fragment("snuffle", {}),
    new Fragment("snug", {}),
    new Fragment("so'ton", {}),
    new Fragment("soap", {}),
    new Fragment("sock", {}),
    new Fragment("sock", {}),
    new Fragment("socks", {}),
    new Fragment("soft", {}),
    new Fragment("soil", {}),
    new Fragment("soiled", {}),
    new Fragment("solemn", {}),
    new Fragment("solo", {}),
    new Fragment("son", {position: Position.END}),
    new Fragment("son-son", {position: Position.END}),
    new Fragment("sonic", {position: Position.START}),
    new Fragment("sore", {}),
    new Fragment("sores", {position: Position.END}),
    new Fragment("soul", {}),
    new Fragment("soup", {}),
    new Fragment("sour", {}),
    new Fragment("south", {}),
    new Fragment("sovereign", {}),
    new Fragment("spag", {}),
    new Fragment("spaghetti", {}),
    new Fragment("spam", {}),
    new Fragment("spammer", {}),
    new Fragment("spangled", {}),
    new Fragment("sparkle", {}),
    new Fragment("sparkly", {}),
    new Fragment("spasm", {}),
    new Fragment("special", {}),
    new Fragment("specs", {}),
    new Fragment("speedy", {position: Position.START}),
    new Fragment("spelunk", {}),
    new Fragment("spelunker", {}),
    new Fragment("spelunking", {}),
    new Fragment("spender", {}),
    new Fragment("spenny", {}),
    new Fragment("sperg", {}),
    new Fragment("sphere", {}),
    new Fragment("spice", {}),
    new Fragment("spiced", {}),
    new Fragment("spicy", {position: Position.START}),
    new Fragment("spider", {}),
    new Fragment("spiders", {}),
    new Fragment("spiky", {}),
    new Fragment("spit", {}),
    new Fragment("splash", {}),
    new Fragment("splasher", {}),
    new Fragment("splat", {Position: Position.END}),
    new Fragment("splats", {Position: Position.START}),
    new Fragment("spleen", {}),
    new Fragment("splurge", {}),
    new Fragment("sponge", {}),
    new Fragment("spongy", {}),
    new Fragment("sponsor", {}),
    new Fragment("spooge", {}),
    new Fragment("spooger", {position: Position.END}),
    new Fragment("spoon", {}),
    new Fragment("sport", {}),
    new Fragment("sports", {}),
    new Fragment("spots", {}),
    new Fragment("spotted ", {position: Position.START}),
    new Fragment("sprocket", {}),
    new Fragment("spruce", {}),
    new Fragment("spruce", {}),
    new Fragment("spry", {}),
    new Fragment("spud", {}),
    new Fragment("spud", {}),
    new Fragment("square", {}),
    new Fragment("squid", {}),
    new Fragment("squishy", {}),
    new Fragment("stain", {}),
    new Fragment("stained", {}),
    new Fragment("stains", {}),
    new Fragment("stale", {}),
    new Fragment("stallion", {}),
    new Fragment("stan", {}),
    new Fragment("starboard", {}),
    new Fragment("stash", {}),
    new Fragment("steal", {}),
    new Fragment("stealer", {}),
    new Fragment("stealth", {}),
    new Fragment("steam", {}),
    new Fragment("steamer", {}),
    new Fragment("steaming", {}),
    new Fragment("steamy", {}),
    new Fragment("steed", {}),
    new Fragment("steel", {}),
    new Fragment("steely", {}),
    new Fragment("stench", {}),
    new Fragment("step", {}),
    new Fragment("step", {}),
    new Fragment("stern", {}),
    new Fragment("stew", {}),
    new Fragment("stick", {}),
    new Fragment("sticky", {}),
    new Fragment("sting", {}),
    new Fragment("stinger", {}),
    new Fragment("stingy", {}),
    new Fragment("stink", {}),
    new Fragment("stinker", {}),
    new Fragment("stinky", {}),
    new Fragment("stolen", {}),
    new Fragment("stollen", {}),
    new Fragment("stoned", {}),
    new Fragment("stones", {}),
    new Fragment("stonk", {}),
    new Fragment("stonker", {}),
    new Fragment("stony", {}),
    new Fragment("stooge", {}),
    new Fragment("stool", {}),
    new Fragment("stoop", {}),
    new Fragment("storm", {position: Position.END}),
    new Fragment("strained", {}),
    new Fragment("strap", {}),
    new Fragment("strategy", {}),
    new Fragment("strawberry", {}),
    new Fragment("stream", {}),
    new Fragment("streamer", {}),
    new Fragment("strimmer", {}),
    new Fragment("stroker", {}),
    new Fragment("strummer", {}),
    new Fragment("strumpet", {}),
    new Fragment("stucco", {}),
    new Fragment("stupid", {}),
    new Fragment("style", {}),
    new Fragment("styles", {}),
    new Fragment("succ", {}),
    new Fragment("sucker", {}),
    new Fragment("suckle", {}),
    new Fragment("suckler", {}),
    new Fragment("sugar", {}),
    new Fragment("suit", {}),
    new Fragment("summoner", {}),
    new Fragment("sunny", {position: Position.START}),
    new Fragment("super", {}),
    new Fragment("sus", {}),
    new Fragment("suspect", {}),
    new Fragment("suspects", {}),
    new Fragment("suspicious", {}),
    new Fragment("swab", {}),
    new Fragment("swallow", {}),
    new Fragment("swallower", {}),
    new Fragment("swamp", {}),
    new Fragment("swamper", {}),
    new Fragment("swamping", {}),
    new Fragment("swan", {}),
    new Fragment("swanning", {}),
    new Fragment("swash", {}),
    new Fragment("sweary", {}),
    new Fragment("sweet", {}),
    new Fragment("swindler", {position: Position.END}),
    new Fragment("swing", {}),
    new Fragment("swinger", {}),
    new Fragment("swinging", {}),
    new Fragment("swings", {}),
    new Fragment("sword", {}),
    new Fragment("symphony", {}),
    new Fragment("synergy", {}),
    new Fragment("synyster ", {position: Position.START}),
    new Fragment("tables", {position: Position.END}),
    new Fragment("tache", {}),
    new Fragment("tackle", {}),
    new Fragment("tackler", {}),
    new Fragment("tactical", {}),
    new Fragment("tadpole", {}),
    new Fragment("taint", {}),
    new Fragment("talkie", {}),
    new Fragment("tar", {}),
    new Fragment("tart", {}),
    new Fragment("tarty", {}),
    new Fragment("taste", {}),
    new Fragment("taster", {}),
    new Fragment("tasty", {}),
    new Fragment("tea", {}),
    new Fragment("teal", {}),
    new Fragment("teams", {}),
    new Fragment("tease", {}),
    new Fragment("techno", {}),
    new Fragment("teller", {}),
    new Fragment("temperance ", {position: Position.START}),
    new Fragment("tense", {}),
    new Fragment("terminally ", {position: Position.START}),
    new Fragment("terrible", {position: Position.ALONE}),
    new Fragment("tester", {position: Position.END}),
    new Fragment("testines", {position: Position.END}),
    new Fragment("testy", {}),
    new Fragment("tetchy", {}),
    new Fragment("the ", {position: Position.START}),
    new Fragment("thicc", {}),
    new Fragment("thief", {}),
    new Fragment("thin", {}),
    new Fragment("three ", {position: Position.START, type: Type.FORENAME}),
    new Fragment("thrift", {}),
    new Fragment("thrifty", {}),
    new Fragment("throbber", {}),
    new Fragment("thrush", {}),
    new Fragment("thrust", {}),
    new Fragment("thrusted", {}),
    new Fragment("thruster", {}),
    new Fragment("thrusty", {}),
    new Fragment("thunder", {position: Position.START}),
    new Fragment("thyme", {}),
    new Fragment("ticket", {}),
    new Fragment("tickle", {}),
    new Fragment("tickled", {}),
    new Fragment("tickler", {}),
    new Fragment("tie", {}),
    new Fragment("tied", {}),
    new Fragment("ties", {}),
    new Fragment("tiffin", {}),
    new Fragment("time", {}),
    new Fragment("tin", {}),
    new Fragment("tinder", {}),
    new Fragment("tiny", {}),
    new Fragment("tit", {position: Position.END}),
    new Fragment("tit", {}),
    new Fragment("tits", {}),
    new Fragment("titty", {}),
    new Fragment("Titus ", {position: Position.START}),
    new Fragment("toast", {}),
    new Fragment("toad", {}),
    new Fragment("toilet", {}),
    new Fragment("ton", {position: Position.END}),
    new Fragment("tone", {}),
    new Fragment("too", {}),
    new Fragment("tool", {}),
    new Fragment("toot", {}),
    new Fragment("tooter", {}),
    new Fragment("tooting", {}),
    new Fragment("tosser", {}),
    new Fragment("totem", {}),
    new Fragment("touch", {}),
    new Fragment("touched", {}),
    new Fragment("toucher", {}),
    new Fragment("town", {}),
    new Fragment("train", {}),
    new Fragment("tram", {}),
    new Fragment("treacle", {}),
    new Fragment("treat", {}),
    new Fragment("trick", {}),
    new Fragment("tricker", {}),
    new Fragment("trickle", {}),
    new Fragment("tricky", {}),
    new Fragment("trippin", {}),
    new Fragment("trousers", {}),
    new Fragment("trumpet", {}),
    new Fragment("tumbler", {}),
    new Fragment("tumblr", {}),
    new Fragment("turd", {}),
    new Fragment("turkey", {}),
    new Fragment("turtle", {}),
    new Fragment("turtleneck", {position: Position.ALONE}),
    new Fragment("tweeter", {}),
    new Fragment("twig", {}),
    new Fragment("twiggy", {}),
    new Fragment("twigs", {}),
    new Fragment("twin", {}),
    new Fragment("twister", {}),
    new Fragment("twisty", {}),
    new Fragment("uber", {position: Position.START}),
    new Fragment("unable", {}),
    new Fragment("under ice", {}),
    new Fragment("undercover ", {position: Position.START}),
    new Fragment("undesirable ", {position: Position.START}),
    new Fragment("unholy", {}),
    new Fragment("unlicensed", {}),
    new Fragment("unsanctioned", {position: Position.ALONE}),
    new Fragment("up", {position: Position.START}),
    new Fragment("urgh", {}),
    new Fragment("ussio", {position: Position.END}),
    new Fragment("ussy", {position: Position.END}),
    new Fragment("uwu", {}),
    new Fragment("vampire", {}),
    new Fragment("van", {}),
    new Fragment("various ", {position: Position.START, type: Type.FORENAME}),
    new Fragment("veg", {}),
    new Fragment("vegetable", {}),
    new Fragment("vegetal", {}),
    new Fragment("veloci", {position: Position.START}),
    new Fragment("velvet", {}),
    new Fragment("vengeful", {}),
    new Fragment("venus", {}),
    new Fragment("verge", {}),
    new Fragment("verve", {}),
    new Fragment("vice", {}),
    new Fragment("vimes", {position: Position.ALONE, type: Type.SURNAME}),
    new Fragment("vinegar", {}),
    new Fragment("vinted", {}),
    new Fragment("violet", {}),
    new Fragment("virtual", {}),
    new Fragment("visceral ", {position: Position.START}),
    new Fragment("void", {}),
    new Fragment("von ", {position: Position.START, type: Type.SURNAME}),
    new Fragment("wafer", {}),
    new Fragment("waffer", {}),
    new Fragment("waffle", {}),
    new Fragment("waffle", {}),
    new Fragment("wag", {}),
    new Fragment("wailer", {position: Position.ALONE}),
    new Fragment("wailer", {position: Position.END}),
    new Fragment("walkie", {}),
    new Fragment("wallop", {}),
    new Fragment("walloper", {}),
    new Fragment("wallow", {}),
    new Fragment("wallower", {}),
    new Fragment("war", {}),
    new Fragment("warlike", {}),
    new Fragment("warlock", {}),
    new Fragment("warner", {}),
    new Fragment("warning", {}),
    new Fragment("warrior", {}),
    new Fragment("water", {}),
    new Fragment("wave", {}),
    new Fragment("waved", {}),
    new Fragment("waver", {}),
    new Fragment("wavey", {}),
    new Fragment("way", {}),
    new Fragment("wayward", {}),
    new Fragment("weapon", {}),
    new Fragment("weary", {}),
    new Fragment("weasel", {}),
    new Fragment("wedge", {}),
    new Fragment("weed", {}),
    new Fragment("ween", {}),
    new Fragment("weenie", {}),
    new Fragment("weevil", {}),
    new Fragment("weiner", {}),
    new Fragment("well", {}),
    new Fragment("wellness", {}),
    new Fragment("wench", {}),
    new Fragment("wenis", {}),
    new Fragment("werther's", {}),
    new Fragment("west", {}),
    new Fragment("wet", {}),
    new Fragment("wetter", {}),
    new Fragment("whale", {}),
    new Fragment("wheel", {}),
    new Fragment("whimper", {}),
    new Fragment("whimpering", {}),
    new Fragment("whisper", {}),
    new Fragment("whispering", {}),
    new Fragment("who art in heaven", {position: Position.ALONE, type: Type.SURNAME}),
    new Fragment("wide", {}),
    new Fragment("widget", {}),
    new Fragment("wiggle", {}),
    new Fragment("wiggled", {}),
    new Fragment("wiggler", {}),
    new Fragment("wiggum", {}),
    new Fragment("wild", {}),
    new Fragment("wildin", {}),
    new Fragment("willow", {}),
    new Fragment("willy", {}),
    new Fragment("wily", {}),
    new Fragment("wimp", {}),
    new Fragment("wince", {}),
    new Fragment("window", {position: Position.START}),
    new Fragment("wine", {}),
    new Fragment("winged", {}),
    new Fragment("winner", {}),
    new Fragment("wise", {}),
    new Fragment("wisp", {}),
    new Fragment("wispy", {}),
    new Fragment("wispy", {}),
    new Fragment("witch", {}),
    new Fragment("witchy", {position: Position.START}),
    new Fragment("within", {}),
    new Fragment("wizard", {position: Position.END}),
    new Fragment("wocky", {}),
    new Fragment("woeful", {}),
    new Fragment("wolf", {}),
    new Fragment("wololo", {}),
    new Fragment("wombat", {}),
    new Fragment("womble", {position: Position.END}),
    new Fragment("womble", {}),
    new Fragment("wonder", {}),
    new Fragment("wonk", {}),
    new Fragment("wonky", {}),
    new Fragment("woo", {}),
    new Fragment("wood", {}),
    new Fragment("woof", {}),
    new Fragment("wook", {}),
    new Fragment("wookie", {}),
    new Fragment("wool", {}),
    new Fragment("wop", {}),
    new Fragment("worm", {}),
    new Fragment("worms", {}),
    new Fragment("worry", {}),
    new Fragment("worst", {}),
    new Fragment("worth", {position: Position.END}),
    new Fragment("worth", {}),
    new Fragment("wound", {}),
    new Fragment("wow! ", {position: Position.START}),
    new Fragment("wrangler", {position: Position.END}),
    new Fragment("wretched", {}),
    new Fragment("wriggle", {}),
    new Fragment("wriggled", {}),
    new Fragment("wriggler", {}),
    new Fragment("wumbo", {}),
    new Fragment("wumpus", {}),
    new Fragment("wunder", {}),
    new Fragment("wurst", {}),
    new Fragment("yank", {}),
    new Fragment("yanked", {}),
    new Fragment("yanker", {}),
    new Fragment("yanking", {}),
    new Fragment("yawning", {position: Position.ALONE, type: Type.FORENAME}),
    new Fragment("yearning", {position: Position.ALONE, type: Type.FORENAME}),
    new Fragment("yeast", {}),
    new Fragment("yeasty", {}),
    new Fragment("yee", {}),
    new Fragment("yeehaw", {}),
    new Fragment("yeezy", {}),
    new Fragment("yell", {}),
    new Fragment("yeller", {}),
    new Fragment("yelling", {}),
    new Fragment("yoghurt", {}),
    new Fragment("yolo", {}),
    new Fragment("zero", {}),
    new Fragment("zoo", {}),
    new Fragment("zoom", {}),
    new Fragment("zoot", {}),
]


export default fragments;
